# docker-compose.dev.yml
version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: gpt-collab-backend
    depends_on:
      - mongodb
    ports:
      - "${BACKEND_EXPOSE:-5000}:${BACKEND_PORT:-5000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=${BACKEND_PORT:-5000}
      - MONGODB_URI=mongodb://mongodb:${MONGODB_PORT:-27017}/${MONGODB_DATABASE:-gpt_collab}
      - JWT_SECRET=${JWT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JUDGE0_API_KEY=${JUDGE0_API_KEY}
      - JUDGE0_API_URL=${JUDGE0_API_URL}
      - JUDGE0_API_HOST=${JUDGE0_API_HOST}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:3000}
    volumes:
      - ./backend:/app
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: gpt-collab-frontend
    depends_on:
      - backend
    ports:
      - "${FRONTEND_EXPOSE:-3000}:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=http://localhost:${BACKEND_EXPOSE:-5000}
      - REACT_APP_SOCKET_URL=http://localhost:${BACKEND_EXPOSE:-5000}
      - REACT_APP_RAPID_API_URL=${JUDGE0_API_KEY}
      - REACT_APP_RAPID_API_HOST=${JUDGE0_API_URL}
      - REACT_APP_RAPID_API_KEY=${JUDGE0_API_HOST}
    volumes:
      - ./frontend:/app
    command: yarn start

  mongodb:
    image: mongo:7-jammy
    container_name: gpt-collab-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    ports:
      - "${MONGODB_EXPOSE:-27017}:${MONGODB_PORT:-27017}"
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE:-gpt_collab}
    networks:
      - gpt-collab-network
    command: mongod --port ${MONGODB_PORT:-27017}

networks:
  gpt-collab-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local