version: '3.8'

services:
  # Main application service
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/gpt-collab-dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-development-jwt-secret-change-in-production}
      - CLIENT_URL=http://localhost:3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JUDGE0_API_KEY=${JUDGE0_API_KEY}
      - JUDGE0_API_HOST=${JUDGE0_API_HOST:-judge0-ce.p.rapidapi.com}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      # Development specific
      - VITE_API_URL=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/client/node_modules
      - /app/server/node_modules
      - /app/client/dist
    depends_on:
      - mongo
      - redis
    restart: unless-stopped
    networks:
      - app-network
    stdin_open: true
    tty: true
    # Enable hot reload
    command: npm run dev

  # MongoDB database
  mongo:
    image: mongo:6
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_DATABASE=gpt-collab-dev
    volumes:
      - mongo_data_dev:/data/db
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data_dev:/data
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # MongoDB Express (Database Admin UI)
  mongo-express:
    image: mongo-express:latest
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017/gpt-collab-dev
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-admin123}
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - tools

  # Redis Commander (Redis Admin UI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "${REDIS_COMMANDER_PORT:-8082}:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - app-network
    profiles:
      - tools

volumes:
  mongo_data_dev:
    driver: local
  redis_data_dev:
    driver: local

networks:
  app-network:
    driver: bridge